### ISSUE TITLE
Possible conflict induced by the name of the repository

### ISSUE THREAD

**Issue by vds2212** [nordtheme/vim#338]
This is not exactly a bug but a doubt.

When installing the theme as a plugin using vim-plug the theme is installed into: `.vim/plugged/vim`

For the time being it is fine but if others do the same there will be a conflict about the `vim` name that seems not very nord specific. Maybe the `vim` folder should be renamed `nord_vim`?

The installation instructions needs also to be adapted.

**Comment by ericvw** [comment]
This is similar to https://github.com/orgs/nordtheme/discussions/188.

You can use the [`as` option](https://github.com/junegunn/vim-plug#plug-options) in vim-plug. For example:

```vim
call plug#begin()
Plug 'nordtheme/vim', {'as': 'nordtheme'}
call plug#end()
```

**Comment by vds2212** [comment]
Thanks for your answer.

It is indeed a solution but it introduces a complexity that is avoidable.

It is not may call I just wanted to be sure it has been discussed :-)
